apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider-service
  template:
    metadata:
      labels:
        app: rider-service
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: app
          image: 225632394198.dkr.ecr.eu-west-2.amazonaws.com/ridehail/rider-service:1.0.0
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rider-service
spec:
  selector:
    app: rider-service
  ports:
    - port: 80
      targetPort: 8000
